pipeline {
	agent any
	tools {
	    maven "MAVEN3.9"
	    jdk "JDK17"
	}

	stages {

	    stage('Fetch code') {
            steps {
               git branch: 'atom', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
	    }

	    stage('Build'){
	        steps{
	           sh 'mvn install -DskipTests'
	        }
	        post {
	           success {
	              echo 'Now Archiving it...'
	              archiveArtifacts artifacts: '**/target/*.war'
	           }
	        }
	    }

	    stage('UNIT TEST') {
            steps{
                sh 'mvn test'
            }
        }

        stage('Checkstyle Analysis') {
            steps{
                sh 'mvn checkstyle:checkstyle'
            }
        }

        stage("Sonar Code Analysis") {
        	environment {
                scannerHome = tool 'sonar6.2'
            }
            steps {
              withSonarQubeEnv('sonarserver') {
                sh '''
            java -version
            echo $JAVA_HOME
            ${scannerHome}/bin/sonar-scanner \\
                -Dsonar.projectKey=vprofile \\
                -Dsonar.projectName=vprofile \\
                -Dsonar.projectVersion=1.0 \\
                -Dsonar.sources=src/ \\
                -Dsonar.java.binaries=target/classes/ \\
                -Dsonar.junit.reportsPath=target/surefire-reports/ \\
                -Dsonar.jacoco.reportsPath=target/jacoco.exec \\
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            '''
          }
        }
      }
    }
}